<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>Leave</fullName>
        <description>Leave</description>
        <protected>false</protected>
        <recipients>
            <recipient>prerna.tiwary1991@eternussolutions.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>prerna.tiwary1@eternussoluions.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>prerna.tiwary@eternussolutions.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/SupportSelfServiceResetPassword</template>
    </alerts>
    <alerts>
        <fullName>Leaves</fullName>
        <description>Leaves</description>
        <protected>false</protected>
        <recipients>
            <recipient>East_Manager</recipient>
            <type>role</type>
        </recipients>
        <recipients>
            <recipient>West_Manager</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/MarketingProductInquiryResponse</template>
    </alerts>
    <tasks>
        <fullName>tdfgdc</fullName>
        <assignedTo>prerna.tiwary1991@eternussolutions.com</assignedTo>
        <assignedToType>user</assignedToType>
        <dueDateOffset>0</dueDateOffset>
        <notifyAssignee>false</notifyAssignee>
        <priority>Normal</priority>
        <protected>false</protected>
        <status>In Progress</status>
        <subject>tdfgdc</subject>
    </tasks>
</Workflow>
